### Exercício: Análise de Desempenho de Clubes no Campeonato Brasileiro 2024

#### Objetivo:

- Manipular dados de um campeonato de futebol
- Calcular e visualizar estatísticas de desempenho dos clubes.

#### Passo 1: Leitura da Planilha

Carregar os dados do arquivo `brasileirao.xlsx` usando pandas.

In [1]:
import pandas as pd
df = pd.read_excel("brasileirao.xlsx")

In [ ]:
df.head()

                  Clube   V   E   D  GP  GC  Saldo de Gols  Pontos
0      Atlético Mineiro   5   8  25  55  30             25      23
1  Athletico Paranaense  15   5  18  34  27              7      50
2                 Bahia  12  10  16  42  51             -9      46
3              Botafogo  10   8  20  28  25              3      38
4            Bragantino  20   8  10  51  46              5      68
5           Corinthians  18   4  16  41  24             17      58
6              Cruzeiro  10   5  23  55  59             -4      35
7                Cuiabá  15   7  16  58  39             19      52
8              Flamengo   9   2  27  22  24             -2      29
9            Fluminense  14   9  15  28  48            -20      51

In [ ]:
df.sort_values("V", ascending=False)

#### Passo 2: Calcular o saldo de gols (SG)

Adicionar uma nova coluna chamada "Saldo de gols" que será a diferença entre Gols Pró (`GP`) e Gols Contra (`GC`).

In [5]:
df["Saldo de Gols"] = df["GP"] - df["GC"]
df.sort_values("Saldo de Gols", ascending=False)

                   Clube   V   E   D  GP  GC  Saldo de Gols
14             Palmeiras  20   2  16  54  25             29
0       Atlético Mineiro   5   8  25  55  30             25
7                 Cuiabá  15   7  16  58  39             19
5            Corinthians  18   4  16  41  24             17
15             São Paulo   9   8  21  36  23             13
11                Grêmio  15   8  15  27  20              7
1   Athletico Paranaense  15   5  18  34  27              7
4             Bragantino  20   8  10  51  46              5
3               Botafogo  10   8  20  28  25              3
10             Fortaleza   8   3  27  25  25              0
12         Internacional   5   4  29  56  56              0
17               Vitória  16   5  17  55  56             -1
8               Flamengo   9   2  27  22  24             -2
13             Juventude  12   3  23  50  53             -3
6               Cruzeiro  10   5  23  55  59             -4
2                  Bahia  12  10  16  42  51             -9
18   Atlético Goianiense  16   5  17  43  52             -9
19              Criciúma  13   5  20  45  57            -12
9             Fluminense  14   9  15  28  48            -20
16         Vasco da Gama   7   8  23  27  52            -25

#### Passo 3: Calcular a pontuação total

Criar uma coluna chamada "Pontos" onde a pontuação será calculada da seguinte forma:

- Vitória (`V`) = 3 pontos.
- Empate (`E`) = 1 ponto.
- Derrota (`D`) = 0 pontos.

In [7]:
df["Pontos"] = (df["V"] * 3) + df["E"]
df.sort_values("Pontos", ascending=False)

                   Clube   V   E   D  GP  GC  Saldo de Gols  Pontos
4             Bragantino  20   8  10  51  46              5      68
14             Palmeiras  20   2  16  54  25             29      62
5            Corinthians  18   4  16  41  24             17      58
11                Grêmio  15   8  15  27  20              7      53
17               Vitória  16   5  17  55  56             -1      53
18   Atlético Goianiense  16   5  17  43  52             -9      53
7                 Cuiabá  15   7  16  58  39             19      52
9             Fluminense  14   9  15  28  48            -20      51
1   Athletico Paranaense  15   5  18  34  27              7      50
2                  Bahia  12  10  16  42  51             -9      46
19              Criciúma  13   5  20  45  57            -12      44
13             Juventude  12   3  23  50  53             -3      39
3               Botafogo  10   8  20  28  25              3      38
6               Cruzeiro  10   5  23  55  59             -4      35
15             São Paulo   9   8  21  36  23             13      35
16         Vasco da Gama   7   8  23  27  52            -25      29
8               Flamengo   9   2  27  22  24             -2      29
10             Fortaleza   8   3  27  25  25              0      27
0       Atlético Mineiro   5   8  25  55  30             25      23
12         Internacional   5   4  29  56  56              0      19